### ISSUE TITLE
Dynamic object keys issue

### ISSUE THREAD

**Issue by chrisblossom** [gcanti/babel-plugin-tcomb#100]
I am unable to get dynamic object keys working. I am not sure if I am doing something wrong inside of flow or if there is different syntax for flow and this plugin.

``` ts
type ObjectTypes = {
  exists: string;
  sometimesExists?: string;

  // If any other keys exist, they should follow this pattern:
  [field: string]: {
    some: number;
  };
};

const passes_flow1 = (): ObjectTypes => {
  return {
    exists: 'some string',
    other: {
      some: 123,
    },
  };
};

const passes_flow2 = (): ObjectTypes => {
  return {
    exists: 'some string',
  };
};

const fails_flow1 = (): ObjectTypes => {
  return {
    exists: 'some string',
    sometimesExists: 'other string',
    other: {
      some: 'should be a number',
    },
  };
};

console.log(passes_flow1());
console.log(passes_flow2());
console.log(fails_flow1());
```

https://github.com/chrisblossom/tcomb-objects : [entry.js](https://github.com/chrisblossom/tcomb-objects/blob/master/entry.js)

If you run `npm run build` it will fail, but `npm run flow` works as expected.

**Comment by gcanti** [comment]
Didn't know you can mix maps and records

```js
type ObjectTypes = {
  exists: string;
  sometimesExists?: string;

  // If any other keys exist, they should follow this pattern:
  [field: string]: {
    some: number;
  };
};
```

Definitely this syntax is not supported

**Comment by chrisblossom** [comment]
Thanks for the reply. Anyway I can work around it? I am unsure how to declare a dynamic object that is not static until created (with the above schema). Maybe I am "abusing" flow maps?
