### ISSUE TITLE
.flowconfig ignored

### ISSUE THREAD

**Issue by fgarcia** [gcanti/babel-plugin-tcomb#102]
Right after installing `babel-plugin-tcomb` I got errors about missing global declarations.

I have seen there is a `globals` option but could not see how to link my global declaration file. In any case, I would expect the plugin to load the flow checker using my current `.flowconfig` file

**Comment by gcanti** [comment]
> could not see how to link my global declaration file

There's no such a feature at the moment. Global types must be set through the `globals` option
