### ISSUE TITLE
incorrect runtime failure when using 'keyword'-style function arguments

### ISSUE THREAD

**Issue by nrser** [gcanti/babel-plugin-tcomb#103]
i often use "keyword-style" function arguments with es6 destructuring:

```javascript
function f({x = 'ex'} = {}) {
  console.log({x});
}
```

where 

```javascript
f()
f({x: 'blah'})
```

are both legitimate calls.

i'm trying to add type checking, and i may be doing it wrong, but i've gotten flow to agree with this (never mind how ugly it is):

```javascript
function f({x = 'ex'}: {x?: string} = {}) {
  console.log({x});
}
```

but tcomb then rejects the `f()` call:

```
TypeError: [tcomb] Invalid value undefined supplied to arguments[0]: {x: ?String}
```

the compiled code looks like:

```javascript
function f() {
  var _ref = arguments.length <= 0 || arguments[0] === undefined ? {} : arguments[0];

  var _ref$x = _ref.x;
  var x = _ref$x === undefined ? 'ex' : _ref$x;

  _assert(arguments[0], _tcomb2.default['interface']({
    x: _tcomb2.default.maybe(_tcomb2.default.String)
  }), 'arguments[0]');

  console.log({ x: x });
}
```

the issue appears to be that tcomb is checking against `arguments[0]`, which does not receive the default `{}` parameter (it gets assigned to `_ref`).

**Comment by gcanti** [comment]
@nrser pushed a fix on the `103` branch if you want to try it out:

```
npm r babel-plugin-tcomb
npm i gcanti/babel-plugin-tcomb#103
```

**Comment by nrser** [comment]
so awesome. will give it a spin.

**Comment by nrser** [comment]
yup, seems to work great. thanks so much.
