### ISSUE TITLE
How to import class declarations from interface files?

### ISSUE THREAD

**Issue by volkanunsal** [gcanti/babel-plugin-tcomb#113]
I've been using the third party library declarations quite a lot lately and I've created a bunch of these:

```js
declare class Foo {
  bar(o: number): number
}
```

The problem is `babel-plugin-tcomb` doesn't recognize these class declarations. I thought about a few options. Adding a global for each class, which is not scalable, or duplicating the class definitions as a type and importing them from the interface file, which is redundant. Is there anything else I'm overlooking here?

**Comment by oleander** [comment]
Any solution to this problem? Using interfaces my self and is currently getting `ReferenceError: X is not defined`.
