### ISSUE TITLE
flow Class<C> syntax causes ReferenceError at runtime

### ISSUE THREAD

**Issue by nrser** [gcanti/babel-plugin-tcomb#115]
flow lets you define a class type via `Class<C>` syntax:

https://flowtype.org/docs/classes.html#classt-type

for which the tcomb babel plugin generates a runtime checks if the value is an instance of `Class`, which doesn't exist, causing a `ReferenceError` at runtime:

```javascript
function f(errorClass: Class<Error>): Error {
  return new errorClass("hey");
}
```

compiles to

```javascript
function f(errorClass) {
  _assert(errorClass, Class, "errorClass");

  var ret = function (errorClass) {
    return new errorClass("hey");
  }.call(this, errorClass);

  _assert(ret, Error, "return value");

  return ret;
}
```

producing

```
  _assert(errorClass, Class, "errorClass");
                      ^

ReferenceError: Class is not defined
```

**Comment by gcanti** [comment]
https://github.com/gcanti/babel-plugin-tcomb/issues/86

**Comment by nrser** [comment]
thanks for the rapid response. i'm looking for it to actually check that `errorClass` is a subclass of `Error`, so turning it into an `Any` check doesn't really help me. i worked around it with a refinement for the moment:

```js
function isErrorClass(obj: *): boolean {
  return obj.prototype instanceof Error;
}

type ErrorClass = any & $Refinement<typeof isErrorClass>;
```

i'm sure you know much better than i how much of a pain implementing that sort of functionality from `Class<Error>` would be, but if you want to point me towards some spots on the source i'd be down to give it try if i have some time.

**Comment by gcanti** [comment]
> i'm looking for it to actually check that **errorClass is a subclass of Error**

Maybe I'm missing something but what about just using `Error`?

```js
class MyError extends Error {}

function foo(e: Error): void {
  console.log(e)
}

foo(new Error()) // <= ok
foo(new MyError()) // <= ok
console.log(MyError.prototype instanceof Error) // => true
```

**Comment by gcanti** [comment]
Actually I did miss something, you want to pass a constructor not an instance, sorry

```js
function f(errorClass: Class<Error>): Error {
  return new errorClass("hey");
}
```

**Comment by gcanti** [comment]
The right sport on the source should be the `getGenericTypeAnnotation` function, before the `shouldReturnAnyType` check.

```js
if (name === 'Object') {
  return getObjectType()
}
if (name === 'Class') {
  // new implementation here
  // should return a type representing Class<T>
}
if (shouldReturnAnyType(name, typeParameters)) {
  return getAnyType()
}
```

What `Class<T>` should be translated to? Following your example I guess something like

```js
t.refinement(t.Function, f => f.prototype instanceof T) // <= where T is the type parameter of Class
```

Unless `T` is something that can't be handled by babel-plugin-tcomb (i.e when `shouldReturnAnyType(T, typeParameters) === true`)

**Comment by nrser** [comment]
yeah, that's how i would approach it... i'm no expert on Javascript's some-what convoluted OO setup; i got the `f.prototype instanceof T` check off a google search but it seems to work.

i would venture to guess that addressing the case where the type variable (or whatever `T` is called above) is an actual class (like `Error`) and not a generic would cover the most common uses.

it's a totally contrived example but you can do things like

```js
// @flow

interface I<T> {
  getClass(): Class<T>;
}

export class A {
  getClass(): Class<A> {
    return this.constructor;
  }
}

function getClass<T>(instance: I<T>): Class<T> {
  return instance.getClass();
}

const a = new A();

console.log(getClass(a) === A);
```

that flow accepts, but i imagine it's quite another step to get into runtime checks on that sort of stuff.
