### ISSUE TITLE
tcomb+flow with babel 5?

### ISSUE THREAD

**Issue by eddiesholl** [gcanti/babel-plugin-tcomb#117]
Hey there,

I'm keen to use this plugin to try out tcomb in an app, but its ember, and they have not yet added support for babel 6. Is there any way to get babel compilation of flow to tcomb in babel 5?

Looking through the release history, it looks like the tcomb plugin last supported babel 5 in v 0.1.5, but the flow to tcomb plugin is v6 only?

Any ideas appreciated. Cheers,

Eddie

**Comment by amilajack** [comment]
Most likely going to be v6 only.

**Comment by gcanti** [comment]
Yes, v6 only, sorry

**Comment by amilajack** [comment]
@eddiesholl I would recommend updating to babel 6. What's holding you back
