### ISSUE TITLE
Promise<any> issue

### ISSUE THREAD

**Issue by chrisblossom** [gcanti/babel-plugin-tcomb#118]
I am running into an issue where when I am specifying a returned promise

``` js
const someFn = (): Promise<any> => somePromisedFn();
```

I am getting the following error:

``` js
   [TypeError: [tcomb] Invalid value {
     "_c": [],
     "_s": 0,
     "_d": false,
     "_h": 0,
     "_n": false
   } supplied to return value (expected a wrappedPromise)],
```

I am basically having to specify all Promised returned functions using comments so tcomb will ignore the flow syntax, for example:

``` js
const someFn = () /* :Promise<any> */ => somePromisedFn();
```

I am unable to reproduce the error in a sandboxed environment so I am having an issue tracking down what I am doing wrong. Any ideas how to debug or fix would be very much appreciated.

**Comment by christophehurpeau** [comment]
do you have a dependency that use `bluebird` or some other package that overrides the global Promise object ?

**Comment by chrisblossom** [comment]
I am including the ``babel-polyfill``, which is probably overriding the Promise object. Think that could be causing an issue?
