### ISSUE TITLE
Recursive type issue

### ISSUE THREAD

**Issue by tquetano-r7** [gcanti/babel-plugin-tcomb#125]
I am having an issue with recursive types and wondering if there is something I'm missing ... can't seem to find anything in the documentation on it. A simple example:

```javascript
type Foo = {
  bar: Array<Foo>
};
```

gives me the following error:

```
fail.js?a676:2Uncaught TypeError: [tcomb] Invalid argument type undefined supplied to list(type, [name]) combinator (expected a type)
```

Any ideas?

**Comment by gcanti** [comment]
```js
// recursive
type Foo = {
  bar: Array<Foo>
};
```

https://github.com/gcanti/babel-plugin-tcomb#recursive-types

**Comment by tquetano-r7** [comment]
bloody hell, I'm an idiot. sorry and thanks!
