### ISSUE TITLE
return types on fat-arrow functions lose access to `this`

### ISSUE THREAD

**Issue by nrser** [gcanti/babel-plugin-tcomb#134]
i'm using version `0.3.17` and seeing fat-arrow functions lose their `this` binding when they have return types declared.

source:

```js
export class A {
  constructor() {
    this.x = 'ex';
  }
  
  f() {
    [1, 2, 3].forEach((n): string => {
      console.log(this.x);
    });
  }
}

const a = new A();
a.f();
```

compiled with `skipAsserts = false`:

```js
// ...

var A = exports.A = function () {
  function A() {
    _classCallCheck(this, A);

    this.x = 'ex';
  }

  _createClass(A, [{
    key: 'f',
    value: function f() {
      [1, 2, 3].forEach(function (n) {
        var ret = function (n) {
          console.log(this.x);
        }.call(this, n);

        _assert(ret, _tcomb2.default.String, 'return value');

        return ret;
      });
    }
  }]);

  return A;
}();

var a = new A();
a.f();

// ...
```

running produces

```
          console.log(this.x);
                          ^

TypeError: Cannot read property 'x' of undefined
```

works fine with `skipAsserts = true`:

```js
// ...

var A = exports.A = function () {
  function A() {
    _classCallCheck(this, A);

    this.x = 'ex';
  }

  _createClass(A, [{
    key: 'f',
    value: function f() {
      var _this = this;

      [1, 2, 3].forEach(function (n) {
        console.log(_this.x);
      });
    }
  }]);

  return A;
}();

var a = new A();
a.f();

// ...
```

notice the `_this = this` and `_this.x` that are missing from the top compilation.

for now i just set `skipAsserts = true` to mitigate it. thanks in advance, Neil.

**Comment by nrser** [comment]
just noticed that the return type on the fat arrow function doesn't make any sense but it shouldn't make any difference.

**Comment by gcanti** [comment]
Ah sure, thanks for reporting. Here https://github.com/gcanti/babel-plugin-tcomb/blob/master/src/index.js#L530 I wrongly used an identifier but there is a proper ast node: thisExpression. Will fix asap

**Comment by gcanti** [comment]
Released a fix

**Comment by nrser** [comment]
awesome, i'll upgrade and try it out
