### ISSUE TITLE
"keyword"-style args with function defaults that declare return types cause runtime errors

### ISSUE THREAD

**Issue by nrser** [gcanti/babel-plugin-tcomb#136]
first off, thanks for being so incredibly on top of these issues.

second, i beginning to think that "keyword" args / defaults might just be bad idea in the current js ecosystem ;)

anyways, with `skipAsserts = false` this code fails with `ReferenceError: _this is not defined`:

```js
function dump({
  obj,
  dumper = (obj: *): string => "object: " + obj,
  //                 ^ problematic!
}: {
  obj: *,
  dumper?: (obj: *) => string,
}): string {
  return dumper(obj);
}

console.log(dump({obj: 1}));
```

you an see the issue in the compiled js:

```js
function dump(_ref) {
  var obj = _ref.obj;
  var _ref$dumper = _ref.dumper;
  var dumper = _ref$dumper === undefined ? function (obj) {
    _assert(obj, _tcomb2.default.Any, "obj");

    var ret = function (obj) {
      return "object: " + obj;
    }.call(_this, obj);
    //     ^ bad reference

    _assert(ret, _tcomb2.default.String, "return value");

    return ret;
  } : _ref$dumper;

  _assert({
    obj: obj,
    dumper: dumper
  }, _tcomb2.default.interface({
    obj: _tcomb2.default.Any,
    dumper: _tcomb2.default.maybe(_tcomb2.default.Function)
  }), "{ obj, dumper }");

  var ret = function (_ref2) {
    var _this = this;
    // ^ because it's declared in this scope

    var obj = _ref2.obj;
    var _ref2$dumper = _ref2.dumper;
    var dumper = _ref2$dumper === undefined ? function (obj) {
      _assert(obj, _tcomb2.default.Any, "obj");

      var ret = function (obj) {
        return "object: " + obj;
      }.call(_this, obj);

      _assert(ret, _tcomb2.default.String, "return value");

      return ret;
    } : _ref2$dumper;

    return dumper(obj);
  }.call(this, {
    obj: obj,
    dumper: dumper
  });

  _assert(ret, _tcomb2.default.String, "return value");

  return ret;
}
```

the `_this` that the `dumper` default function is looking for is declared in the main function's `ret` block, out of it's scope (at least that's what it looks like is happening to me).

works fine when `skipAsserts = true` or the return type is omitted on `dumper`. passes flow. using version `0.3.19`.

**Comment by gcanti** [comment]
It's probably due to how default values are handled by this plugin: note that the default dumper is defined twice. I think it can be fixed by defining the default dumper separately

```js
const defaultDumper = (obj): string => "object: " + obj

function dump({
  obj,
  dumper = defaultDumper,
}: {
  obj: *,
  dumper?: (obj: *) => string,
}): string {
  return dumper(obj);
}
```

**Comment by nrser** [comment]
yeah, it's not that hard to work around (can also just set the default "by hand" in the function body), but it's confusing since it works fine until you declare a return type for the defaulted function *and* the main function:

```js
// works:

function dump({
  obj,
  dumper = (obj: *) => "object: " + obj,
}): string {
  return dumper(obj);
}

// works:

function dump({
  obj,
  dumper = (obj: *): string => "object: " + obj,
}) {
  return dumper(obj);
}

// breaks:

function dump({
  obj,
  dumper = (obj: *): string => "object: " + obj,
}): string {
  return dumper(obj);
}
```

this is obviously a minimal test case; it was much harder to track down the error where it actually occurred.

if it's not something that's going to be supported i understand; it's just a weird caveat to explain to people: "functions that use destructured object parameters with defaults values that are functions may not have a return type declared on both the default value function and the function itself" or something like that.

**Comment by gcanti** [comment]
> it was much harder to track down the error where it actually occurred

You are right, I must find a way to fix this. What if I strip the defaults from the wrapper function?

Example: now this

```js
function dump({
  obj,
  dumper = (obj): string => "object: " + obj,
}): string {
  return dumper(obj);
}
```

compiles to

```js
function dump({
  obj,
  dumper = obj => {
    const ret = function (obj) {
      return "object: " + obj;
    }.call(this, obj);

    _assert(ret, _t.String, "return value");

    return ret;
  }
}) {
  const ret = function ({ obj, dumper = obj => {
      const ret = function (obj) {
        return "object: " + obj;
      }.call(this, obj);

      _assert(ret, _t.String, "return value");

      return ret;
    } }) {
    return dumper(obj);
  }.call(this, {
    obj,
    dumper
  });

  _assert(ret, _t.String, "return value");

  return ret;
}
```

Note that `dumper` is defined twice. Should compile to

```js
function dump({
  obj,
  dumper = obj => {
    const ret = function (obj) {
      return "object: " + obj;
    }.call(this, obj);

    _assert(ret, _t.String, "return value");

    return ret;
  }
}) {
  const ret = function ({ obj, dumper }) {
    return dumper(obj);
  }.call(this, {
    obj,
    dumper
  });

  _assert(ret, _t.String, "return value");

  return ret;
}
```

Am I right? This change should fix this issue (without an actual implementation I'm just guessing for now)

**Comment by gcanti** [comment]
Yes, it *seems* to work fine. Pushed to 136 branch, could please try it out?

**Comment by gcanti** [comment]
Hi @nrser, may I merge the branch and publish the fix?

**Comment by nrser** [comment]
sorry i haven't had time to look at evaluate this. for now i've just gone set `skipAsserts=false` for my projects... i need return types for flow and i've run into too many issues with the return type checking functionality in `babel-plugin-tcomb`.

the plugin's tendency to default to `t.All` when it can't resolve or doesn't support something has been an issue too; it has given me a false sense of security only to later discover that it was allowing anything through.

for now i'm going back to manual runtime type checks where necessary and hoping flow catches the rest of the issues statically (i've also found flow to "just let anything through" when it doesn't resolve an imported type correctly, which has also been a problem, though it seems to have gotten better with recent releases).

thank you so much for your time and amazing support. i really like `tcomb` and understand that the babel integration is incredibly difficult. i wish i had the luxury to continue using it but it keeps taking me off track when i have an incredible amount of product-critical work on my plate. i hope to come back to it in the near future.

**Comment by gcanti** [comment]
> it keeps taking me off track when i have an incredible amount of product-critical work on my plate

@nrser I understand and for what it's worth I agree with your choice

> for now i'm going back to manual runtime type checks where necessary

FYI I'm exploring the other way around: build a static type from a runtime schema: [flow-runtime](https://github.com/gcanti/flow-runtime)
