### ISSUE TITLE
Regression with de-structuring and default parameters

### ISSUE THREAD

**Issue by masylum** [gcanti/babel-plugin-tcomb#148]
We've updated `babel-plugin-tcomb` to the new version `0.3.20` and this code no longer works:

```js
type Options = {
  add?: boolean;
}

function foo ({ add = true }: Options = {}) {
  // ...
}

foo()
// Uncaught TypeError: [tcomb] Invalid value undefined supplied to { add = true }: Options
```

Any clue? In the changelog I saw there were some changes in de-structuring so this may be related.

**Comment by gcanti** [comment]
This is the produced code

```js
function foo() {
  // ...

  var _ref = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : {},
      _ref$add = _ref.add,
      add = _ref$add === undefined ? true : _ref$add;

  _assert(arguments[0], Options, "{ add = true }"); // <= wrong assert
}
```  

Notice that the assert is performed on `arguments[0]`, which is wrong.

A possible fix is to write this instead

```js
arguments[0] !== undefined ? arguments[0] : {} // <= where this is the default
```

**Comment by masylum** [comment]
Shouldn't be `_ref`?

**Comment by gcanti** [comment]
AFAIK `_ref` is produced by another babel plugin (which likely runs after `babel-plugin-tcomb`) so I can't use it

**Comment by gcanti** [comment]
You can try the fix with (`148` branch):

```
npm r babel-plugin-tcomb
npm i gcanti/babel-plugin-tcomb#148
```

**Comment by gcanti** [comment]
https://github.com/gcanti/babel-plugin-tcomb/releases/tag/v0.3.23

**Comment by masylum** [comment]
Sorry to re-open this issue but I just found that this is broken in this case too:

```js
type Options = {
  optimist: boolean; // <-- Notice that `optimist` is mandatory
}

function foo ({ optimist = true }: Options = {}) {
  // ...
}

foo()
// Uncaught TypeError: [tcomb] Invalid value undefined supplied to { optimist = true }: Options
```

My understanding is that this type should work anyway since `optimist` will always be set in that scenario.
