### ISSUE TITLE
Add a configuration that warns about type mismatch but does not throw an error

### ISSUE THREAD

**Issue by gajus** [gcanti/babel-plugin-tcomb#152]
Working on a large base (transforming into using types), I prefer first adding type annotations to all functions that I think expect a particular type. Then run the code and see if/ where it breaks. At the moment, it always breaks at the first error, therefore I cannot see whether it is a single outlier of a prevalent error.

**Comment by gcanti** [comment]
@gajus something like `warnOnFailure: boolean` (default `false`) and then `console.warn(message)` (instead of throwing)?

**Comment by gajus** [comment]
Sounds like it.

I have temporarily worked around this limitation by modifying `./node_modules/tcomb/index.js`, adding `t.fail = (message) => { console.warn(message); };`

**Comment by gcanti** [comment]
@gajus just pushed an implementation in the `152` branch, could you please try it out on your codebase? (`lib` is commited in so you can install the new version from github: `npm i gcanti/babel-plugin-tcomb#152`)

**Comment by gajus** [comment]
Works perfectly.

<img width="794" alt="screen shot 2016-11-28 at 12 25 39" src="https://cloud.githubusercontent.com/assets/973543/20668258/c4fd022e-b565-11e6-9d2e-7ba7779e90fe.png">

**Comment by gcanti** [comment]
Thanks, will publish asap

**Comment by gcanti** [comment]
Released https://github.com/gcanti/babel-plugin-tcomb/releases/tag/v0.3.24
