### ISSUE TITLE
Refinements example

### ISSUE THREAD

**Issue by yarax** [gcanti/babel-plugin-tcomb#155]
In `Refinements` section there is an example with using predicats. 
Could you please explain how Flow checks predicats, because I don't get it, according to declaration file, Refinements type is just an object. I tried it, but it doesn't work as described in documentation.
```
foo(2)   // flow ok, tcomb ok
```

https://flowtype.org/try/#0CYUwxgNghgTiAEAXAngBwQBTsAlmKiCAvPABQAeAXPFAHbICU8RAfPAEYD2nEIdA3AChBoSLAQp08ACQAlEADMctEAFsQtRAB4M1LCFz5CbEgG8AvkMFhOtAM6J4OOwElNIAOYgYzeLWZs-gCk8ACMzEQkAAyCkghuhF4+JLQArqrs3vAAZDLySirqmlpxnApOru5JLFYKqbRgiDi28ArcpLTUCZ7eTKaC8PBwiKkw-rSC5sI29o7Jre0ArAxWM3Y8IAB0EJwepDAMQA

**Comment by gcanti** [comment]
@yarax there's a misunderstanding here, this plugin adds runtime asserts, it doesn't use Flow under the hood nor replaces Flow capabilities (= static type checking)

**Comment by yarax** [comment]
I understand  that. 
I mean it should at least maintain backward compatibility with Flow, but with example in documentation Flow raises an error, which you can see by the link above

**Comment by gcanti** [comment]
Ah sorry, I misread your question. It's my fault, in a recent refactoring I wrongly replaced

```js
declare interface $Refinement<P: (x: any) => boolean> {}
```

with 

```js
declare type $Refinement<P: Predicate> = {};
```

**Comment by gcanti** [comment]
This should work

[try](https://flowtype.org/try/#0CYUwxgNghgTiAEAXAngBwQBTsAlmKiCAvPABQAeAXPFAHbICU8RAfPAEYD2nEIdA3AChBoSLAQ5ahGADMoYBABIASiBmSQAWxBSAPBmpYQufITYBvAL7CwnWgGdE8HPYCSUkAHMQMZvFrMbAEApPAAjMxEJAAMgijo8O6E3r4ktACumuw+8ABk8CpqGtp68SCcMs5uHiksQoIy6bRgiDh28DLcpLTUSV4+TOaC8PBwiOkwAbSC1oK2Dk6pHV0ArAz18-Y8IAB0EJyepDAMQA)

**Comment by yarax** [comment]
Cool, now it's clear, thanks

**Comment by gcanti** [comment]
Thanks to you for pointing out
