### ISSUE TITLE
"ReactClass is not defined" error

### ISSUE THREAD

**Issue by omerzach** [gcanti/babel-plugin-tcomb#165]
Trying to enable babel-plugin-tcomb for my codebase but getting this error in my `connect` function:
```
Uncaught ReferenceError: ReactClass is not defined
    at connect (connect.js:8)
```

I totally believe my types are incorrect here, but I think `ReactClass` is a real thing? https://github.com/facebook/flow/blob/master/lib/react.js#L96

Here's my code: https://gist.github.com/omerzach/c94285c8626154736b85576f19f1d6e6

**Comment by gcanti** [comment]
You have to configure the plugin (https://github.com/gcanti/babel-plugin-tcomb#globals-arrayobject) when using a global type

**Comment by omerzach** [comment]
👌 thanks!
