### ISSUE TITLE
Add support for object type spread

### ISSUE THREAD

**Issue by voldern** [gcanti/babel-plugin-tcomb#169]
Flow has added support for spreading flow object types into other object types. See https://github.com/facebook/flow/issues/1326.

These should be converted into a tcomb intersection. One way to do this could be to look for members that are `ObjectTypeSpreadProperty` here: https://github.com/gcanti/babel-plugin-tcomb/blob/master/src/index.js#L393. 

Then we could extract those out, create an interface of the remaining ones and then creating an intersection.

For our use case we also make the objects that we spread $Exact<> in order to make the types be non-mabye. See https://github.com/facebook/flow/issues/3534. tcomb spread doesn't seem to have the same limitation, so we could/should probably just discard the $Exact<> when spreading.

**Comment by voldern** [comment]
Gave it a try :point_up:

**Comment by gcanti** [comment]
> These should be converted into a tcomb intersection

Based on this [comment](https://github.com/facebook/flow/issues/3534#issuecomment-287580240) they are pretty different from intersections

**Comment by voldern** [comment]
> Based on this comment they are pretty different from intersections

Ah, that's true. I was a bit quick on the trigger.

Seems like doing [t.interface.extend()](https://github.com/gcanti/tcomb/blob/master/docs/API.md#extending-interfaces) will be the right thing to do?

**Comment by voldern** [comment]
Updated PR to do `interface.extend` instead.

**Comment by gcanti** [comment]
I'm afraid is not well suited: from the documentation of `tcomb` you linked

> Note. Repeated props are not allowed (unless they are strictly equal)

Also, in absence of official documentaton (!), the following rules seem to apply

- every property from spread becomes optional
- every property before non-exact spread becomes `mixed`
- properties after spread stay the same
- `$Exact` changes the rules above

so the behavior is way different from `t.interface.extend`

**Comment by voldern** [comment]
Thank you so much for the feedback.

Aha. I understood
> Alternatively you can use the t.interface.extend(mixins: Array<Mixin>, options?: string | Options) => TcombType function:

To mean that I could use `t.interface.extend` to allow repeated props.

> every property from spread becomes optional

Would an approach be to iterate over the properties in the interface being spread and make them into `maybe` by default, but not when the interface is `$Exact<>`?

> every property before non-exact spread becomes mixed

We could do this by splitting properties into two groups, before and after spread and making those before spread `mixed` ?

And then using extend to join these properties together, given that `t.interface.extend` allows repeated props. If not we could maybe do some hand-wrangling to create a new interface directly?

**Comment by voldern** [comment]
Would a way to simplify this be to add an option to [.extend()](https://github.com/gcanti/tcomb/blob/master/lib/interface.js#L120) that allow overwrites that gets passed to [mixin()](https://github.com/gcanti/tcomb/blob/master/lib/extend.js#L45). Or would you rather not allow this in plain `tcomb` ?

**Comment by gcanti** [comment]
IMO the better option would be to define an helper function (actually a new custom tcomb combinator) and inject when needed, like `assert` or `extend` (see here https://github.com/gcanti/babel-plugin-tcomb/blob/master/src/index.js#L64). Since `tcomb` types are fully introspectable at runtime, you should be able to implement the required complex logic.

**Comment by voldern** [comment]
I've updated the pr and I think it takes in to account all of the strange rules surrounding the object spread. How do you feel about the code, and the separation between what is done at compile time vs runtime?

**Comment by gcanti** [comment]
> How do you feel about the code, and the separation between what is done at compile time vs runtime?

Seems a good balance. Let me know when you consider the PR mergeable. If you agree I'll publish this feature tagged as `Experimental` for now

> From the CHANGELOG file: A feature tagged as Experimental is in a high state of flux, you're at risk of it changing without notice.

because

- the upstream feature seems yet unstable
- the feature must be tested in real world scenarios

**Comment by voldern** [comment]
:+1:

I've bumped the version and updated the changelog. Is there anything I've missed? If not I feel like its mergable.
