### ISSUE TITLE
Consider supporting an alternative format for default param type annotations.

### ISSUE THREAD

**Issue by ctrlplusb** [gcanti/babel-plugin-tcomb#18]
Currently the following syntax is supported:
```
function foo(bar = 1 : t.Number) 
```

Would you be up for us to support the following additional syntax:
```
function foo(bar : t.Number  = 1) 
``` 

It seems like Flow annotations seemed to have followed this additional style.  Therefore tools like EsLint don't complain for this format, however, they throw errors on the current syntax.

**Comment by gcanti** [comment]
Ah, this is weird. I opted for the first syntax since with the second syntax babel seems to strip out the types:

```js
// source

function foo(x: t.Number, y = 1: t.Number) {
  return x + y;
}

function bar(x: t.Number, y: t.Number = 1) {
  return x + y;
}
```

```js
// compiled

function foo(x: t.Number, y = 1: t.Number) {
  t.assert(t.Number.is(x));
  t.assert(t.Number.is(y));

  return x + y;
}

function bar(x: t.Number, y = 1) { // <= y type stripped out
  t.assert(t.Number.is(x));

  return x + y;
}
```

**Comment by ctrlplusb** [comment]
Hmmm, oki, will look into this further.  Perhaps just an eslint issue...

**Comment by gcanti** [comment]
Released in https://github.com/gcanti/babel-plugin-tcomb/releases/tag/v0.2.2
