### ISSUE TITLE
a few issues

### ISSUE THREAD

**Issue by giogonzo** [gcanti/babel-plugin-tcomb#2]
Hi there, I'm trying to use babel-tcomb-plugin here: https://github.com/buildo/avenger/pull/82 and it is working really well for now!

A few issues a run into:

**ret function in non-binded class methods**

here: https://github.com/buildo/avenger/blob/avenger-81-use_babelplugintcomb/src/Avenger.js#L73 I'd like to type the return value as `PromiseType` (`instanceof Promise`). The generated code looks something like:
```js
Avenger.prototype.run = function run(input, state) {
  input = _types.AvengerInput(input);
  state = _types.State(state);

  var ret = function (input, state) {
    var _this2 = this;

    // ...

    return //...
  }(input, state);

  return _types.PromiseType(ret);
};
```
No matter what tcomb type annotation I use there, but I get many problems due to `this` being `undefined` inside `ret = function(input, state) { ... }`.
I could either bind the method myself in class declaration or handle with more care the invocation everywhere else in my code, but.. what if the generated code was something like the following instead?
```js
Avenger.prototype.run = function run(input, state) {
  input = _types.AvengerInput(input);
  state = _types.State(state);

  var ret = (function (input, state) {
    var _this2 = this;

    // ...

    return //...
  }).call(this, input, state);

  return _types.PromiseType(ret);
};
```

**types and default value for arrow functions params**

Not sure about what you could do on your side here (didn't look at the code yet), but I wasn't able to apply both a type annotation and a default value here: https://github.com/buildo/avenger/blob/avenger-81-use_babelplugintcomb/src/util.js#L20 and in other similar cases.. any suggestion?

What I'm trying to do is: `export const collect = (o: t.Object, map: t.Function = v => v) => ...`

**Comment by gcanti** [comment]
> what if the generated code was something like the following instead?

:+1:

new commit on master if you want to give it a whirl.

> types and default value for arrow functions params

under investigation...

**Comment by giogonzo** [comment]
> new commit on master if you want to give it a whirl.

works flawlessly, thanks!

**Comment by gcanti** [comment]
Closing in favour of #3
