### ISSUE TITLE
Should we assert that an import of tcomb occurred?

### ISSUE THREAD

**Issue by ctrlplusb** [gcanti/babel-plugin-tcomb#21]
Transpile output is:
```
const f = x => {
  t.assert(t.String.is(x));
  return x;
};
```

Therefore if `t` isn't in scope the user will get runtime errors.  I can put a check within the plugin that will assert for a tcomb import.

What do you think?

**Comment by ctrlplusb** [comment]
I have the work done to support this.  It throws a helpful error stating that tcomb needs to be imported.

Also fixes a bug when using an import from one of the extended libraries.  The following currently throws:
```
import { t, propTypes } from 'tcomb-react';
```

Let me know if you think it's a good addition.

**Comment by ctrlplusb** [comment]
Ok, also have it working for `require` based imports.

**Comment by gcanti** [comment]
Definitely interesting. Could you please send a PR?

**Comment by ctrlplusb** [comment]
Stress testing it against my massive existing project and then will send it right through.

Its defo helpful though.  See:
<img alt="screenshot 2016-04-26 17 42 00" src="https://cloud.githubusercontent.com/assets/12164768/14827631/36b92de6-0bdb-11e6-90c6-db8bf29f9808.png">

**Comment by gcanti** [comment]
Released in https://github.com/gcanti/babel-plugin-tcomb/releases/tag/v0.2.2
