### ISSUE TITLE
Assert on structure not specific instance type?

### ISSUE THREAD

**Issue by ctrlplusb** [gcanti/babel-plugin-tcomb#22]
Hi, not sure if this is expected behaviour. 

Given the following:
```
const Person = t.struct({
  name: t.String,
  surname: t.String
}, `Person`);

function hello(x : Person) {
  return 'Hello ' + x.name;
}
```

Executing the following errors:
```
hello({ name: `jon`, surname: `doe`});
```

Whereas the following does not:
```
hello(Person({ name: `jon`, surname: `doe`}));
```

This seems a bit overly strict in my opinion.  I know it transpiles to:
```
t.Assert(Person.is(x));
```

Do you think it's worth it and possible to relax the rules so that we assert the structure only?

Sometimes I just want to wrap a complex argument object into a local struct and not necessarily expose the type.

**Comment by ctrlplusb** [comment]
Nice one!

Can look at transpiling to:
```
Person(x)
```

Which throws right? :)

**Comment by gcanti** [comment]
> Do you think it's worth it and possible to relax the rules so that we assert the structure only?

It would be confusing if you use a method in the function body:

```js
const Person = t.struct({
  name: t.String,
  surname: t.String
}, `Person`);

Person.prototype.getFullName = function () {
  return `${this.name} ${this.surname}`;
};

function hello(x : Person) {
  // here you do rely on x being a Person...
  return 'Hello ' + x.getFullName();
}

// ...instead you get a TypeError
hello({ name: `jon`, surname: `doe`}); // throws "TypeError: x.getFullName is not a function"
```

**Comment by ctrlplusb** [comment]
Very good point! I'll look into a typed destructure instead.

**Comment by ctrlplusb** [comment]
Hmm, desctructured type checking throws Babel into a hissy fit.  Closing.
