### ISSUE TITLE
Nice to have: eslint plugin to allow for "unused" t imports.

### ISSUE THREAD

**Issue by ctrlplusb** [gcanti/babel-plugin-tcomb#26]
EsLint isn't intelligent enough to pick up the relationship with an import of t which isn't being used directly.  e.g.
```
import t from 'tcomb';
import { Person } from './types';
function hello(person: Person) {
...
}  
```

This can cause build fails on strict setups.  

You can create an .eslintrc rule as so to naively fix this:
```
    "no-unused-vars": ["error", { "vars": "all", "args": "after-used", "varsIgnorePattern": "t" }],
```

That will ignore any unused vars with the identifier of `t`.  

Of course this isn't bulletproof though, so an intelligent AST based eslint plugin that is a reverse of #21 could be useful.

This is strictly for the most pedantic of us.

**Comment by gcanti** [comment]
Isn't this redundant now that we have #21?

**Comment by ctrlplusb** [comment]
Sorry, brain fart!  I completely described that backwards.  I've edited the title and OP.

**Comment by ctrlplusb** [comment]
Awesome!  That is great to see.

I have been snowed under but my deadline approaches.  Looking forward to being able to contribute!
