### ISSUE TITLE
add support for default values

### ISSUE THREAD

**Issue by gcanti** [gcanti/babel-plugin-tcomb#3]
This example throws an error with the current implementation

```js
function foo(x: t.Number = 0, y: t.String) {
  return x + y;
}
```

**Comment by ctrlplusb** [comment]
Happy to help with this, but I'll wait for the babel 6 PR (#12) to go through first. :)

**Comment by gcanti** [comment]
@ctrlplusb I think I got a fix https://github.com/gcanti/babel-plugin-tcomb/pull/15

**Comment by gcanti** [comment]
Released https://github.com/gcanti/babel-plugin-tcomb/releases/tag/v0.2.0
