### ISSUE TITLE
0.2.2 breaks noop default params.

### ISSUE THREAD

**Issue by ctrlplusb** [gcanti/babel-plugin-tcomb#31]
```
function(bar = 'foo) {
  return bar;
}
```

**Comment by gcanti** [comment]
@ctrlplusb I have to prepare a patch release or it's better to wait for other changes / bug fix?

**Comment by ctrlplusb** [comment]
@gcanti there are a few other bugs I've come across. All tiny. I'll patch them before you do another release.

**Comment by gcanti** [comment]
@ctrlplusb any update?

**Comment by ctrlplusb** [comment]
Hi @gcanti,  apologies, professional life came and wiped me out.  I'll send a PR this w/end though.

**Comment by ctrlplusb** [comment]
I've created a new PR #32 with additional bugs that I have picked up during my usage.

**Comment by gcanti** [comment]
Thanks! Patch release on its way

**Comment by gcanti** [comment]
Fixed in https://github.com/gcanti/babel-plugin-tcomb/releases/tag/v0.2.3
