### ISSUE TITLE
ReferenceError: Props is not defined

### ISSUE THREAD

**Issue by volkanunsal** [gcanti/babel-plugin-tcomb#45]
I took the code example from README and applied to my React component with tcomb-react. This is the error I'm getting:

```
ReferenceError: Props is not defined
```

Here is my code:

```js
import { props } from 'tcomb-react'

type Props = {
  resourceName: ResourceNameT,
  resourceId: string
}

@props(Props)
export default class UserDefinedField extends React.Component {
...
}
```

Btw, I'm using the master branch of `tcomb-react` as well.

**Comment by gcanti** [comment]
Weird, could you please double check that the `babel-plugin-tcomb` is installed and listed in your `.babelrc` file? Here's mine and it works fine:

```js
{
  "presets": ["es2015", "react"],
  "plugins" : [
    "tcomb",
    "transform-decorators-legacy",
    "transform-class-properties"
  ]
}
```

**Comment by volkanunsal** [comment]
Aha, ok, getting close. It didn't work from .babelrc, but when I put them in webpack loader query, they worked, I think.

Another issue I run into is how to code enums. This doesn't work for me:

```js
const PROJECTS = 'projects'
const DOB_JOBS = 'dob'
type ResourceNameT = PROJECTS | DOB_JOBS
```

```
TypeError: [tcomb] Invalid argument types [ "projects", "dob" ] supplied to union(types, [name]) combinator (expected an array of at least 2 types)
```

**Comment by volkanunsal** [comment]
I realize that this doesn't happen if I use strings directly instead of constants.

```js
type ResourceNameT = 'projects' |  'dob'
```

**Comment by gcanti** [comment]
You must write

```js
type ResourceNameT = 'projects' | 'dob';
```

otherwise both `Flow` and `babel-plugin-tcomb` think that `ResourceNameT` is a union instead of an enum
