### ISSUE TITLE
Global available types like SyntheticEvent are not found

### ISSUE THREAD

**Issue by 0xR** [gcanti/babel-plugin-tcomb#56]
I get this error: ` SyntheticEvent is not defined` when using the type  `SyntheticEvent` in my code.

For some reason flow seems to understand what the type means and `babel-plugin-tcomb` does not. 

I have tried to import the type but that upsets flow:

`import type { SyntheticEvent } from 'react';` gives: `This module has no named export called SyntheticEvent.`

Flow defines this type here: https://github.com/facebook/flow/blob/master/lib/react.js it seems to globally declared, i.e. not tied to any specific module.

It looks like `babel-plugin-tcomb` does not understand globally declared types.

**Comment by gcanti** [comment]
> it seems to globally declared, i.e. not tied to any specific module

Yeah, seems a hack in the file definition. I don't undestand the rationale behind such a choice. Why `SyntheticEvent` is globally declared instead of being an exported type?

**Comment by STRML** [comment]
Is there a way to define global definitions for tcomb, much like Flow's own interfaces files? I have a lot of type helpers we just export as globals because we use them nearly everywhere to paper over some weaknesses in Flow.

**Comment by gcanti** [comment]
> because we use them nearly everywhere to paper over some weaknesses in Flow

@STRML could you please provide an example?

**Comment by STRML** [comment]
Sure - here's a few globals we use:

```js
type NodeCallback<T> = (err?: Error, data: T) => void;

// Usage: 
// Object full of numbers: GenericMap<number>
// Object full of strings with defined keys from some object: GenericMap<string, foo>
type GenericMap<T, U = any> = {[key: $Keys<U>]: T};

type ReactRenderable = React.Element<any> | string | number | boolean;

// Parameterize EventHandler so we can pass the type of event we're handling
type EventHandler2<E: Event & $Subtype<Event> = Event> = (event: E) => any;
type EventListener2<E: Event = Event> = {handleEvent: EventHandler2<E>} | EventHandler2<E>;
```

Flow itself has a number of globals, like `EventHandler` and many others.

**Comment by gcanti** [comment]
I may try to detect globals via babel APIs. If it's not possible or not reliable I may provide a plugin option, something like

```js
"plugins" : [
  ["tcomb", { 
    globals: [
      // react
      {
        'SyntheticEvent': true,
        ...
      },
      // custom
      {
        'NodeCallback': true,
        'GenericMap': true,
        ... 
      }
    ] 
  }],
]
```

and then compile globals to `t.Any` (tcomb equivalent to Flow `any`)

**Comment by gcanti** [comment]
Update: is possible but babel (correctly) detects as global `Promise`, `Map`, `Set` etc.. which are "legal" and should not be compiled to `t.Any`.

**Comment by gcanti** [comment]
Just pushed a `56` branch with a candidate implementation of the `globals` option if you want to try it out (`lib` is committed in, so you can simply `npm install` it)

@STRML btw thanks to your example TIL that I can define a default for a type parameter :)

**Comment by STRML** [comment]
Thanks! I'll try it out.

Re defaults unfortunately it's not at useful as it used to be. That should
allow you not to specify the parameter but that warns now as of 0.28. Been
meaning to add an issue for that. You can of course shut off the warning.

**Comment by STRML** [comment]
Never mind, the error is indeed suppressed if you write a default, so long as you still define a list.

So this is an error:

```js
type EventHandler<E = Event> = (e: E) => void;
const onClick: EventHandler = (e) => void;
```

You have to use an empty list (`<>`):

```js
type EventHandler<E = Event> = (e: E) => void;
const onClick: EventHandler<> = (e) => void;
```
