### ISSUE TITLE
Add support for Variable declarations (const)

### ISSUE THREAD

**Issue by christophehurpeau** [gcanti/babel-plugin-tcomb#59]
Hello !
Destructuring is not checked by tcomb.

```js
const { a }: { a: string } = { a: 'a' };
```
transpiles to:

```js
var _a = { a: 'a' };
const a = _a.a;
```

It works with [babel-plugin-typecheck](https://github.com/codemix/babel-plugin-typecheck):

```js
var _a = { a: 'a' };
const a = _a.a;

if (!(typeof a === 'string')) {
    throw new TypeError('Value of "{\n  a\n}" violates contract.\n\nExpected:\n{ a: string\n}\n\nGot:\n' + _inspect({ a: a }));
}
```

**Comment by gcanti** [comment]
Hi @christophehurpeau,

Variable declarations are not supported at the moment. It shouldn't be too difficult to add them though. I'll mark this issue as a feature request.

**Comment by gcanti** [comment]
Closing as per f69c261cc5dee78dbe8cd152f2673d0d9febde77.

Support for `let`s tracked here https://github.com/gcanti/babel-plugin-tcomb/issues/70
