### ISSUE TITLE
Support for Babel 6

### ISSUE THREAD

**Issue by ctrlplusb** [gcanti/babel-plugin-tcomb#7]
I am sure this is fairly obvious and probably just needs someone (me?) to get on with it.  I thought that it best to have it logged though.

Thanks for the great work on your libraries.

**Comment by gcanti** [comment]
Hi,

Not yet switched to babel 6 at work, but I gladly accept a PR.

**Comment by mlegenhausen** [comment]
+1

**Comment by gcanti** [comment]
Released https://github.com/gcanti/babel-plugin-tcomb/releases/tag/v0.2.0
