### ISSUE TITLE
add support for React prop types?

### ISSUE THREAD

**Issue by gcanti** [gcanti/babel-plugin-tcomb#76]
Along the lines of [babel-plugin-flow-react-proptypes](https://www.npmjs.com/package/babel-plugin-flow-react-proptypes)

**Comment by LeoDT** [comment]
Is this still on your roadmap?

**Comment by gcanti** [comment]
No, I'm contributing to babel-plugin-flow-react-proptypes.

Anyway a basic support is already there: functional components are handled by usual typings

```js
type Props = { name: string };

export const A = (props: Props) => <div>{props.name}</div>
```

while class components can be checked either in the constructor or in the render method

```js
export class B extends React.Component {
  constructor(props: Props) {
    super(props)
  }
  render() {
    (this.props: Props)
    return <div>{this.props.name}</div>
  }
}
```
