### ISSUE TITLE
Aliasing imported types

### ISSUE THREAD

**Issue by minedeljkovic** [gcanti/babel-plugin-tcomb#77]
Is aliasing of imported flow types supported by plugin?

For example I have types imported like this:
```js
import type { Model as FilterModel, Action as FilterAction } from '../filter';
```

but, after babel transformation, I see it in debugger like this:
```js
var _filter = __webpack_require__(672);

var FilterModel = _filter.FilterModel || _tcomb2.default.Any;
var FilterAction = _filter.FilterAction || _tcomb2.default.Any;
```

`FilterModel` and `FilterAction` are `undefined` on `_filter`. 

What would work is:
```js
var _filter = __webpack_require__(672);

var FilterModel = _filter.Model || _tcomb2.default.Any; // _filter.Model instead of _filter.FilterModel
var FilterAction = _filter.Action || _tcomb2.default.Any; // _filter.Action instead of  _filter.FilterAction
```

I tried to investigate further, but I am not very good at debugging babel pipeline. :(

Any ideas?

**Comment by gcanti** [comment]
There a bug: currently `../filter` is wrongly detected as an external import declaration (because it starts with `../`). Thanks for raising this issue. I'll fix this asap

**Comment by gcanti** [comment]
@minedeljkovic just pushed a `77` branch with a possible fix, could you please try it out (`lib` is committed in, so you can simply `npm install` it)

**Comment by minedeljkovic** [comment]
Looks good!

Thanks @gcanti, I know you are fast, but I'm always caught by surprise. :)

**Comment by gcanti** [comment]
Great, thanks for testing, new release on its way...
