### ISSUE TITLE
$Refinement doesn't catch this case

### ISSUE THREAD

**Issue by volkanunsal** [gcanti/babel-plugin-tcomb#78]
I have the following type definition

```js
const isPoly = layer => layer instanceof L.Polyline || layer instanceof L.Polygon || layer instanceof L.Rectangle
type PolyT = Object & $Refinement<typeof isPoly>
```

And I use it this way:

```js
getLayer(e: Object) {
    let ret: PolyT = e.layer || e.target || e   // <= Doesn't throw
    return ret
}

addLayer(e) {
  let layer = this.getLayer()
 if(!isPoly(layer)) { throw new Error('Layer is not a poly') }  // <= Throws
}
```

As it will become clear, the type definition doesn't throw, even though the refinement function returns false. 

The compiled assertion function for this is the following:

```js
function _assert2(x, type, name) {
  if (_tcomb5.default.isType(type) && type.meta.kind !== 'struct') {
    type(x, [name + ': ' + _tcomb5.default.getTypeName(type)]);
  } else if (!(x instanceof type)) {
    _tcomb5.default.fail('Invalid value ' + _tcomb5.default.stringify(x) + ' supplied to ' + name + ' (expected a ' + _tcomb5.default.getTypeName(type) + ')');
  }

  return x;
}
```

Also, it may be relevant that this function is defined twice in the compiled code. The same is true for the calls.

```js
function getLayer(e) {
      _assert2(e, _tcomb3.default.Object, 'e');

      _assert2(e, _tcomb3.default.Object, 'e');


      var ret = e.layer || e.target || e;
      return ret;
}
```

Btw, I just noticed that it  looks like the refinement type is not asserted in the function body at all actually. That seems to be the real issue here.

**Comment by gcanti** [comment]
Hi @volkanunsal, thanks for the detailed issue. Some observations:

`let`s are not supported, use `const`s instead

```js
getLayer(e: Object) {
  const ret: PolyT = e.layer || e.target || e   // <= const
  return ret
}
```

You might even use a type cast in this case

```js
getLayer(e: Object) {
  return (e.layer || e.target || e: PolyT) // <= type cast
}
```

or a typed return value

```js
getLayer(e: Object): PolyT { // <= return value
  return e.layer || e.target || e
}
```

> Also, it may be relevant that this function is defined twice in the compiled code

Make sure you added `"passPerPreset": true` in your babel configuration (https://github.com/gcanti/babel-plugin-tcomb/issues/53)

**Comment by gcanti** [comment]
Also, since your predicate uses only `instanceof` you can define `PolyT` as a union

```js
type PolyT = L.Polyline | L.Polygon || L.Rectangle;
```

**Comment by volkanunsal** [comment]
@gcanti I tried, but I couldn't get the return type to work. Typecasting does work. Also here is my .babelrc file. I do have the `passPerPreset`, it seems.

```json
{
  "presets": ["es2015", "react", "stage-0"],
  "passPerPreset": true,
  "plugins": [
    "tcomb",
    "transform-decorators-legacy",
    "transform-class-properties",
    "syntax-flow",
    "transform-flow-strip-types"
  ]
}
```

**Comment by volkanunsal** [comment]
Oh, sorry, I didn't have `passPerPreset` actually. When I added it just now, I'm getting all sorts of errors from Babel:

```
Module build failed: TypeError: Property name of JSXOpeningElement expected node to be of a type ["JSXIdentifier","JSXMemberExpression"] but instead got "MemberExpression"
```

**Comment by volkanunsal** [comment]
@gcanti I fixed the issue! The problem is when you use more than one presets, as I do, you need to specify them in just the right order. Otherwise, Babel will freak out. Here is the order that worked for me:

```js
presets: ['stage-0', 'react', 'es2015'],
```

**Comment by gcanti** [comment]
> you need to specify them in just the right order

Ah, thanks for explaining. I'll add that to the docs.

p.s.
"syntax-flow" and "transform-flow-strip-types" plugins seem redundant as you are using the "react" preset
