### ISSUE TITLE
Special flow type - Class

### ISSUE THREAD

**Issue by minedeljkovic** [gcanti/babel-plugin-tcomb#86]
Class type (https://flowtype.org/docs/classes.html#classt-type) compiles to a not defined runtime type.

For example:
```js
const theClass: Class<C> = C;
```
compiles to:
```js
const theClass = _assert(C, Class, "theClass");
```
which results in: `ReferenceError: Class is not defined`

Probably the easiest bail out is to treat `Class<T>` as `t.Any`

**Comment by gcanti** [comment]
@minedeljkovic please see https://github.com/gcanti/babel-plugin-tcomb/issues/56
