### ISSUE TITLE
Passing mismatch description from $Refinement predicate

### ISSUE THREAD

**Issue by brabeji** [gcanti/babel-plugin-tcomb#91]
Hello @gcanti 

I'm using `$Refinement` to typecheck my values. Is there a way to pass additional information about type mismatch from the predicate? Specifically I'm testing if value is valid JSON Schema like this

```
const isJSONSchema = (x) => {
	const errors = validate(x); // some validator function for JSON Schema
	if (errors.length) {
		return false;
		// I would like to somehow return the errors, 
		// so tcomb can print them in typecheck result
	}
	return true;
};

export type JsonSchema = Object & $Refinement<typeof isJSONSchema>;
```

Now I get only something like
```
TypeError: [tcomb] Invalid value {
  "$ref": "#/definitions/Post",
  "definitions": {
    "Post": {
      "type": "objectt", // invalid and hard to spot in large schema :(
      "x-model": "Post",
      "allOf": [
        {
          "properties": {
            "tags": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        }
      ]
    }
  }
} supplied to schema: JsonSchema
```
even though the validator tells me exact error, which is a pity IMO.

I know that returning, for example, object with errors from predicate can seem (and sure is) ugly if one call that function a predicate. Throwing an `Error` is not an ideal solution either because it is not catched in `$Refinement`. Are there some other options?

I can imagine that this could be discussed elsewhere so excuse me if this is dupe. 

Thank you for awesome libs!

**Comment by gcanti** [comment]
Hi @brabeji,

You may want to replace `Object` with a rich domain model, for example:

```js
type Property = Object; // etc...

type Post = {
  type: 'object',
  'x-model': 'Post',
  allOf: Array<Property>
};

type Definition = Post; // <= actually an union here

type Definitions = {[key: string]: Definition};

type Schema = {
  $ref: string,
  definitions: Definitions
};

const schema: Schema = { // <= throws [tcomb] Invalid value "objectt" supplied to schema: Schema/definitions: Definitions/Post: Post/type: "object" (expected one of ["object"])
  "$ref": "#/definitions/Post",
  "definitions": {
    "Post": {
      "type": "objectt",
      "x-model": "Post",
      "allOf": [
        {
          "properties": {
            "tags": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        }
      ]
    }
  }
}
```

**Comment by brabeji** [comment]
Thanks for quick response. Sure that can be done but it's basically reimplementing http://json-schema.org/draft-04/schema# as `tcomb` type which i try to avoid.

Now when I think about it again, maybe https://github.com/gcanti/tcomb-json-schema will give better message. Going to try it now.

**Comment by brabeji** [comment]
Nope, the message is the same as with predicate. 

If you don't like an idea of catching specific `Error` carrying details about mismatch from predicate of `$Refinement`, this can be closed.

**Comment by gcanti** [comment]
> it's basically reimplementing http://json-schema.org/draft-04/schema# as tcomb type which **i try to avoid**

ah.. ok, I misunderstood your goal

> I know that returning, for example, object with errors from predicate

I'm afraid is not possible, this package builds on tcomb and its refinement signature and internal usage requires a predicate

> Are there some other options?

I wonder... how do you use the `JsonSchema` type? It's used only for type checking as in

```js
function foo(schema: JsonSchema) {
  ...
}
// or
const schema: JsonSchema = ...
```

or you also use the function `JsonSchema.is / isJSONSchema` in your code?

In case of the former, we know that the `JsonSchema.is` function is called only when an assert injected by this plugin is called, so if it returns `false` we also know that something went wrong and we can throw (the plugin will throw right after anyway)

```js
const isJSONSchema = (x) => {
  const errors = validate(x); // some validator function for JSON Schema
  if (errors.length) {
    if (process.env.NODE_ENV !== 'production') { // <= you can skip this check if you don't include babel-plugin-tcomb in production builds
      throw new Error('a message containing the errors')
    }
    return false;
  }
  return true;
}
```

**Comment by brabeji** [comment]
Exactly, I'm using it only to typecheck function parameter. I guess this is the solution for me.

Thank you for your help!
