### ISSUE TITLE
Exported Union type get dispatch stripped off.

### ISSUE THREAD

**Issue by singggum3b** [gcanti/babel-plugin-tcomb#92]
Hi , in case i'm exporting a Union type: 
```
export type JSONComponentListType = JSONComponentType | JSONCloneComponentType;

JSONComponentListType.dispatch = function (value) {
	if (value.cloneID) return JSONCloneComponentType;
	return JSONComponentType;
};
```
```
import type JSONComponentListType;
console.log(JSONComponentListType.dispatch); // ---->still output default Union dispatch
```
if i try to add dispatch after import: 
```
import type JSONComponentListType;
JSONComponentListType.dispatch = function (value) {
	if (value.cloneID) return JSONCloneComponentType;
	return JSONComponentType;
};
```
it still output error whe trying to validate `Array<JSONComponentListType>` : 
```
constructor(tpl: T, componentIndex: Array<JSONComponentListType>) {...}
```
```
Invalid value supplied to componentIndex: Array<JSONComponentListType>/0: JSONComponentListType (no constructor returned by dispatch)
```

**Comment by gcanti** [comment]
Hi, I can't reproduce. I tested against:

```js
// 92.js
type A = { a: number };
type B = { b: string };
export type C = A | B;

C.dispatch = (x) => {
  if (x.hasOwnProperty('a')) {
    return A
  }
  return B
}

// index.js
import type { C } from './92'

class D {
  constructor(x: Array<C>) {}
}

new D([{a: 1}]) // ok
console.log(C.dispatch) // ok
```

babel-plugin-tcomb v0.3.10
babel v6.11.4

Could you please post a complete failing test case?

**Comment by singggum3b** [comment]
Hi @gcanti , can you please try with this repo : `https://github.com/singggum3b/rocket-react` branch master ?
`npm i ` then `npm run dev`; open `localhost:3000`

I tried to update babel-core but it's still not working

**Comment by singggum3b** [comment]
Hey, it's seem the cause is recursive: 
```
// Recursive
export type C = A | B;
```

**Comment by gcanti** [comment]
👍  `tcomb` doesn't handle unions with custom `dispatch`s. https://github.com/gcanti/tcomb/issues/242

A temporary workaround might be moving `JSONComponentListType` below `JSONComponentType` and removing `// recursive`

```js
export type JSONCloneComponentType = {
  ...
}

// recursive
export type JSONComponentType = {
  ...
}

export type JSONComponentListType = JSONComponentType | JSONCloneComponentType
```

Working on a fix in the `tcomb` repo...

**Comment by singggum3b** [comment]
Thanks you for the workaround & definitely love the responsiveness :heart_eyes:

**Comment by gcanti** [comment]
Released a fix in https://github.com/gcanti/tcomb/releases/tag/3.2.11
@singggum3b thanks for reporting this issue
