### ISSUE TITLE
Support for Immutable.js types

### ISSUE THREAD

**Issue by volkanunsal** [gcanti/babel-plugin-tcomb#94]
I've been trying to use Immutable's [List type](https://github.com/facebook/immutable-js/blob/master/type-definitions/immutable.js.flow#L402) in my `t.match` function, but it doesn't seem to work and I get this error. 

![screen shot 2016-08-19 at 5 38 05 pm](https://cloud.githubusercontent.com/assets/151600/17825092/c7c81902-6633-11e6-9d5f-1b92ff7dfbfb.png)

Others, like [Record](https://github.com/facebook/immutable-js/blob/master/type-definitions/immutable.js.flow#L624), do work, though. I used a Refinement type for the List type for now, but I wanted to draw attention to these types and wondered how to support these types more easily...

Here is my code

```js
type ListA = Obj & $Refinement< typeof I.List.isList >
type MapA = Obj & $Refinement< typeof I.Map.isMap >
type RecordA = Record
```

**Comment by gcanti** [comment]
@volkanunsal it seems an issue with tcomb's `match` which currently accepts only types https://github.com/gcanti/tcomb/issues/248
