### ISSUE TITLE
Flow type skip/ignore option

### ISSUE THREAD

**Issue by chrisblossom** [gcanti/babel-plugin-tcomb#98]
I am running into issues where features are supported with flow but not tcomb/this plugin. I am working around this by placing the flow definition inside comments as described [here](https://flowtype.org/blog/2015/02/20/Flow-Comments.html) that this plugin ignores.

Is there a better way to do this? Is there a way I can setup a "skip" option for specific flow types? For example:

```js
/* @flow */

import React from 'react';

const Test = (): React.Element<any> => (
  <div>RETURN REACT ELEMENT</div>
);

export default Test;
```

```js
// the above code returns:
Expecting a function in instanceof check, but got undefined
TypeError: Expecting a function in instanceof check, but got undefined at _assert2
```

I would like to have tcomb ignore ``: React.Element<any>``. As mentioned before, I am getting around this via commenting: ``const Test = () /* :React.Element<any> */ => (``.

**Comment by gcanti** [comment]
`React.Element` is weird, unlike `Component` and `PureComponent` there's no "real" named export called `Element` (hence the plugin breaks). However if you import `Element` as a type it works

```js
import React from 'react'
import type { Element } from 'react'

const Test = (): Element<any> => (
  <div>RETURN REACT ELEMENT</div>
)
```

**Comment by chrisblossom** [comment]
Thanks for the quick reply. Would it be a good idea/possible to import Element/other similar components automatically if not already imported?

Any thoughts on the skip/ignore option? I guess might be more of a hack?

**Comment by gcanti** [comment]
> Would it be a good idea/possible to import Element/other similar components automatically if not already imported?

It's hard because identifiers are mangled by babel so there's no reliable way to do it. For example if you try to fix this issue using the `globals` option (https://github.com/gcanti/babel-plugin-tcomb#globals-arrayobject) you'll find that babel turns `Element` into `_react2.default.Element` so the globals trick doesn't work. 

Another option would be to use global types (for example `React$Element` instead of `Element`)

> Any thoughts on the skip/ignore option? I guess might be more of a hack?

I think would be useful when a use case that cannot be solved otherwise will arise

**Comment by chrisblossom** [comment]
Okay great. Thanks for the help! I'll open a new issue if needed.

**Comment by chrisblossom** [comment]
FYI Using ``React$Element`` I get the following error:

```js
React$Element is not defined
ReferenceError: React$Element is not defined at App 
```

**Comment by gcanti** [comment]
thanks, the `globals` option (https://github.com/gcanti/babel-plugin-tcomb#globals-arrayobject) has been added specifically in order to fix that https://github.com/gcanti/babel-plugin-tcomb/issues/56
